name: Deploy to Azure 

on:
 release:
    types: [published]
 workflow_dispatch:
       
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '13'

      - name: Install dependencies
        run: npm install
      
      - name: Install dependencies
        run: npm install react-scripts@3.0.1 -g

      - name: Build project      
        run: npm run build
        env:          
          REACT_APP_MAPBOX_TOKEN: "${{ secrets.REACT_APP_MAPBOX_TOKEN }}"
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
          CI: ${{ vars.CI }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build"
          output_location: ""
